# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mi7sEgJnK4wOKzaOWFzaxGgfLZ1nz7BT

# Data leakage

Experiment setup: test with 10%...50% attacker knoledge, 100 times
"""

import pandas as pd
import ipaddress
import tensorflow as tf
import numpy as np
from scipy.stats import entropy

"""Create a anonymized list and original list"""

dec_to_bin = lambda ip: bin(int(ipaddress.ip_address(ip)))
bin_to_list = lambda x: [int(d) for d in str(x)]

def transform_binary(ip):
    binary = dec_to_bin(ip)[2:]

    while(len(binary)!=32):
            binary = '0' + binary

    list_binary = bin_to_list(binary)
    return list_binary

df_orig = pd.read_csv('./database/ipv4_df.csv',on_bad_lines='skip', sep=",")
df_anom = pd.read_csv('./results/Tcrypto_Anonimized_24.csv',on_bad_lines='skip', sep=",")

listaOrig = []
vistos = set()
orig = df_orig["IP.src"]
for elemento in orig:
    if elemento not in vistos:
        listaOrig.append(np.array(transform_binary(elemento)).reshape(1, -1) )
        vistos.add(elemento)


listaAnom = []
vistos = set()
anom = df_anom["IP.src"]
for elemento in anom:
    if elemento not in vistos:
        listaAnom.append(np.array(transform_binary(elemento)).reshape(1, -1) )
        vistos.add(elemento)


qtd = []
for i in range(0, len(listaOrig)):
    copy = []
    for j in range(0, len(listaOrig[i])):
        print(listaOrig[i][0][j])
        copy.append(int(listaOrig[i][0][j]))
    qtd.append(entropy(np.array(listaOrig[i][0]).astype(int),base=2))
    
print(qtd)

print(sum(qtd)/len(qtd))

qtd = []
for i in range(0, len(listaAnom)):
    copy = []
    for j in range(0, len(listaAnom[i])):
        print(listaAnom[i][0][j])
        copy.append(int(listaAnom[i][0][j]))
    qtd.append(entropy(np.array(listaAnom[i][0]).astype(int),base=2))
    
print(qtd)

print(sum(qtd)/len(qtd))